### ISSUE TITLE
Suggested change throws unknown error in admin interface

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#103]
Attempting to view this suggested change currently gives me an error
https://civic.genome.wustl.edu/admin/suggested_changes/57

**Comment by acoffman** [comment]
The issue here appears to be that the Variant to which this suggested change was attached no longer exists. It was likely one of the ones that got merged into another. I have cleaned up this suggested change manually. Additionally, I have made it so that when the variant merge tool runs, suggested changes to the removed variant will themselves be removed (as they can't be applied to the remaining variant anyways).
