### ISSUE TITLE
DOID mirror looks like it's missing a couple of diseases

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-server#118]
civic-client issue genome/civic-client#291 refers to a couple of diseases that aren't showing up in the dropdown. I'm assuming these are missing from the local DOID mirror.

```text
hemorrhagic thrombocythemia [DOID: 2224]
chronic myeloproliferative disease [DOID: 2226]
```

**Comment by acoffman** [comment]
@kkrysiak So, I have been using what I believe to be the cancer specific disease ontology dump (latest version here: https://github.com/DiseaseOntology/HumanDiseaseOntology/blob/master/src/ontology/subsets/DO_cancer_slim.obo). Neither of these diseases seems to be in it. Both do appear to be in the full DOID file (https://github.com/DiseaseOntology/HumanDiseaseOntology/blob/master/src/ontology/doid.obo) which is much larger and more complete.

Should I be using the full disease ontology rather than the cancer specific subset?

**Comment by kkrysiak** [comment]
@acoffman Yeah, some of their cancer sections need to be reworked which I actually created a github issue for them about. I doubt that is going to be super fast, it's a pretty complicated reworking that I proposed. Some diseases we now refer to as cancers were not categorized that way not that long ago but clonality analysis (among other things) has changed the game. I'm not sure how many diseases would fall under such an umbrella. Remember, pulling in the rest of disease ontology may result in a repeated synonyms issue which we had kind of punted on since it wasn't a direct problem in the cancer subset (yet).

I think we should discuss this in the group meeting today.

**Comment by kkrysiak** [comment]
It's also interesting to me that Chronic Myeloproliferative Disease is not in the cancer subset. This is kind of a concern since the current relationship scheme has this DOID is_a Myeloma which is_a Bone Marrow Cancer which is_a Hematologic Cancer, etc. It should definitely be in their cancer list.

**Comment by kkrysiak** [comment]
The final decision was to leave it as only the cancer subset. 

Let Disease Ontology know where the obvious cancer entry is missing in their output file that you are using. https://github.com/DiseaseOntology/HumanDiseaseOntology/issues

**Comment by acoffman** [comment]
@kkrysiak I've opened DiseaseOntology/HumanDiseaseOntology#116 to inquire about the inclusion of these diseases.

**Comment by kkrysiak** [comment]
@acoffman this is great. If I see any others, I will add them there.

**Comment by kkrysiak** [comment]
Some other missing diseases - moving these here from https://github.com/genome/civic-server/issues/124 so I could close the duplicate issue.
Her2-receptor positive breast cancer - DOID:0060079
Her2-receptor negative breast cancer - DOID:0060080
triple-receptor negative breast cancer - DOID:0060081

**Comment by malachig** [comment]
Made an update in the DO issue.

**Comment by acoffman** [comment]
I think where we left this was that, for now, we'd just parse the full file and take the cancer subset ourselves. Obviously though, if the Disease Ontology folks are interested in maintaining a file containing the cancer subset themselves - we can just use that!

**Comment by malachig** [comment]
Okay lets do our own thing for now because our need is short term.  But we should also keep them in the loop as we really benefit from their hard work. :)

**Comment by kkrysiak** [comment]
Disease Ontology posted an update to the issue @acoffman opened on their repo so the handful of requested diseases will be live Friday, Feb 19th.

Although they have closed the issue they mention it in an outstanding list of to dos so maybe they will create one down the road: https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/125

**Comment by malachig** [comment]
Here is another one we are missing: 
DOID:5485 synovial sarcoma

**Comment by acoffman** [comment]
I have imported the full cancer subset of the disease ontology into civic and verified that all the mentioned entries are present!

**Comment by malachig** [comment]
Sweet!  Thanks @acoffman this will be awesome for new entries.
