### ISSUE TITLE
Add ability to filter by Submitter in Evidence Items view of admin interface

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#122]
I'm try to review all of the evidence items submitted by a user.  Quite a few have were common germline polymorphisms that have been submitted with `somatic` as the origin.  As discussed we are going to clarify variant origin into three types.  For now I would like to change all of these to 'germline'.

In the Evidence Items view of the Admin interface can we add the ability to filter on the `Submitter`.

@jmcmichael it would be handy if we had this ability in the advanced search page as well.

**Comment by acoffman** [comment]
I've added the ability to filter evidence items by submitter on both the backend admin and advanced search, and the frontend advanced search.

Currently, the grid view that displays the advanced search results is the same as the one that is used on the normal variant summary pages. Because of this, I was hesitant to add "submitter" as a column on that grid. If we need to display different columns on the two pages, it may make sense to split it out into two different components.

Either way, the feature is pushed to master and will go out with the next release!
