### ISSUE TITLE
Unable to accept new evidence item (perhaps because revised before acceptance?)

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-server#137]
I am not able to accept this evidence item:
https://civic.genome.wustl.edu/#/events/genes/37/summary/variants/212/summary/evidence/756/summary#evidence

The pages appears to load but status doesn't change (even after refresh). Also can't accept it through the admin interface. While this evidence statement was still just submitted @kkrysiak suggested a revision which I accepted. I suspect this is causing an issue. I'm not sure but I don't see why we wouldn't want to allow revision of a submitted evidence statement before acceptance (or rejection, if after discussion no revision is sufficient).

**Comment by kkrysiak** [comment]
Oops, I thought I had accepted it. I've been playing with the interface on my iPad and have had some trouble with submissions actually going through, possible due to connectivity issues. 

Perhaps the workflow in this case should be similar to that which was proposed for a rejected evidence item as proposed in issue #131.

**Comment by obigriffith** [comment]
I'm not sure if that is necessary. The accept/reject buttons are still being shown. Maybe just make it so that they work?

**Comment by acoffman** [comment]
This was the same underlying cause as genome/civic-client#320 which is now resolved! I went ahead and accepted the evidence item manually and credited you for doing so!
