### ISSUE TITLE
Only an admin can accept their own revision/evidence item

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#146]
I think it should be a law in CIViC that a user can NOT accept their own changes.  Admins can be an exception to this rule though to allow clean-up by superusers.

**Comment by kkrysiak** [comment]
Maybe we should make that universal for all users, only allowing individuals to accept their own changes through the admin interface. It adds an extra hoop to discourage this behavior, even for admins.

**Comment by malachig** [comment]
Maybe...  some issues are easier to fix in the frontend, while others are easier to fix in the admin interface.

Also, not sure if we get the same event tracking if it is done in the admin interface?  When it does happen we still want the provenance to be recorded.

We could try it and see if it feels like it is holding back cleanup.

**Comment by malachig** [comment]
Lets go with the hard rule.  You can not accept your own proposal (except admins, but even that must be done in the admin interface).

**Comment by acoffman** [comment]
Works for me. Should be pretty easy to implement!

**Comment by acoffman** [comment]
This is now implemented server-side and will go out in the next deploy. The basic ruleset is this:

Users who are at least Editors can accept or reject any evidence item or revision that is not their own.
Users who are Admins can accept or reject any evidence item or revision.
Anyone can reject (but not accept) their own evidence item or revision.

@jmcmichael and I are discussing how to reflect this in the UI so that people understand what is going on!
