### ISSUE TITLE
check out behavior of 'Submitter is' queries on the advanced search endpoint

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-server#160]
This is in reference to genome/civic-client#340. In seeking to display just a single user's evidence items on their profile page, I assumed that the following query might work (despite that we didn't have it in previous Advanced Search forms):

```json
{
   "operator":"AND",
   "queries":[
      {
         "field":"submitter",
         "condition":{
            "name":"is",
            "parameters":[
               "jmcmichael"
            ]
         }
      }
   ]
}
```

However, when I tried displaying the grid on two different user's profile pages, it included the other user's submitted evidence item in the results.

**Comment by acoffman** [comment]
@jmcmichael Yeah, I don't think that'll work "as-is." Since we have the user id already when we're on the profile page, I think it makes sense to use that to do the query. I can either add that (user id) as a valid field on the advanced search, or I can make you an endpoint that gets submitted evidence items (or other activity) for the currently logged in user. Do either of those make sense?

**Comment by jmcmichael** [comment]
Yeah, search by user ID would be perfect.

**Comment by acoffman** [comment]
@jmcmichael added and pushed to master. The field name is `submitter_id` and you'll want to use `is_equal_to` as the operator name.

**Comment by acoffman** [comment]
@jmcmichael this was really simple so I just went ahead and did it!
