### ISSUE TITLE
missing sequence ontology term

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-server#178]
Is it expected that "tandem_duplication" is not available from new Variant Type field.

http://www.sequenceontology.org/miso/release_2.5/term/SO:1000173

**Comment by obigriffith** [comment]
Maybe the sequence_variant but not sequence_feature ontology has been loaded?

**Comment by acoffman** [comment]
@obigriffith that's correct. In the original issue @malachig commented [here](https://github.com/genome/civic-server/issues/102#issuecomment-194572537) that you guys wanted everything under `sequence_variant` imported. I can definitely import a bigger section or another branch if you guys want!

**Comment by kkrysiak** [comment]
Would "[copy_number_increase](http://www.sequenceontology.org/browser/release_2.5/term/SO:0001911)" be an appropriate option in this case? Obviously not totally ideal as some information is lost. We did decide to not bring in the entirety of the ontology at least in part because it seemed as if we could cover everything using only the `sequence_variant` section. There are apparent redundancies between these sections, for instance under `sequence_feature` there is "[copy_number_gain](http://www.sequenceontology.org/browser/release_2.5/term/SO:0001742)" very similar to "copy_number_increase" described above that may only serve to further complicate assigning a variant type. Thus far, I believe all of the [Ensembl/VEP SO mapping choices](http://useast.ensembl.org/info/genome/variation/predicted_data.html) are encompassed by `sequence_variant`, although I haven't systematically confirmed this.

**Comment by obigriffith** [comment]
Hmm. I see the desire to keep it simple as possible. But "tandem_duplication" seems a much better fit for FLT3 ITD than "copy_number_increase". The latter definitely doesn't seem specific enough for such a variant. I think I prefer to have the additional options so that users can choose the term that fits best. We can try to harmonize redundant/equivalent choices through policy/documentation. Or, worst case, a downstream user must query for both "copy_number_increase" and "copy_number_gain". Still a big improvement over current situation where a CNV gain could be described in a hundred different ways without a structured ontology. That's my first instinct anyways. Maybe let's keep going with the SO curation and see how many other times the term we wish we had was only in sequence_feature.

**Comment by kkrysiak** [comment]
I didn't realize you meant FLT3 ITD for some reason I was thinking tandem gene dulications. In that case I would say "[inframe_insertion](http://www.sequenceontology.org/browser/release_2.5/term/SO:0001821)" would be most appropriate under `sequence_variant`.

I agree we should be open to other branches, perhaps we should document them here.

**Comment by kkrysiak** [comment]
My other suggestions are "<a href='http://sequenceontology.org/browser/current_svn/term/SO:0001614'>elongated_in_frame_polypeptide_C_terminal</a>" and/or "<a href='http://sequenceontology.org/browser/current_svn/term/SO:0001557'>polypeptide_gain_of_function_variant</a>".

**Comment by kkrysiak** [comment]
Another instance from Sequence_feature we might be missing in sequence_variant is ["complex_substitution".](http://sequenceontology.org/browser/current_svn/term/SO:1000005)

**Comment by kkrysiak** [comment]
Another from Sequence_feature that would be nice is ["SNP"](http://sequenceontology.org/browser/current_svn/term/SO:0000694) I intended to add it to a variant (ABCB1 S893A/T) before I realized it was under the wrong tree. Not sure how else to tag common polymorphisms.

**Comment by obigriffith** [comment]
We decided to expand to all branches of the SO and see how that goes.

**Comment by acoffman** [comment]
We are now importing all branches of the sequence ontology.
