### ISSUE TITLE
404 Error for Variant

### ISSUE THREAD

**Issue by jakelever** [genome/civic-server#237]
Hey, I'm unsure if I'm doing something wrong. 

When I requested variants from "https://civic.genome.wustl.edu/api/variants?count=1000" I find a variant with ID 211. But when I request that variant specifically (https://civic.genome.wustl.edu/api/variants/211), I get a 404 message.

**Comment by acoffman** [comment]
Hi Jake,

The issue here was that the index endpoint was returning all variants in the database, regardless of if they had any evidence items, while the detail endpoint (ie: `/variants/:id`) did an inner join to evidence items under the assumption that there would always be some.

That variant exists in the system, but has no evidence items, so it was showing in the index endpoint but failing to load on the detail endpoint. This has been addressed and the fix will go out in our next release, tomorrow Friday October 7th.

Going forward, the variants index endpoint will only return variants for which there exists at least one evidence item (of any status) in the system.

Thanks again for your interest in CIViC!

Adam
