### ISSUE TITLE
Decide what MyVariant.info fields to incorporate into the variant view

### ISSUE THREAD

**Issue by acoffman** [genome/civic-server#243]
We already know (from previous issues) that we want:
- Cosmic frequency
- dbsnp rsid

What else do we want to display? ClinVar?

@acoffman provide examples of queries where multiple matching variants are returned.

**Comment by acoffman** [comment]
Example query: http://myvariant.info/v1/variant/chr7:g.140453136A%3ET

**Comment by malachig** [comment]
We should have two tiers of values displayed from myvariant.info and link out to the complete mvariant.info record...  

The first tier will appear along with other variant information in a box that indicates this info is not curated (like we do with gene info from mygene.info).  The second tier will appear as popup box when you hit a `View MyVariant.info Details` button. @kkrysiak , @obigriffith , @arpad and myself came up with the following:

**Candidate tier1 fields**:
clinvar.variant_id
clinvar.rcv.clinical_significance
cosmic.cosmic_id
dbsnp.rsid
emv.egl_classification
exac_nontcga.adj_af
snpeff.ann.effect
snpeff.ann.putative_impact

**Candidate tier 2 fields** (all of the above plus the following):
cadd.consdetail
cadd.consequence
clinvar.HGVS.coding
clinvar.HGVS.genomic
clinvar.HGVS.non-coding
clinvar.HGVS.protein
clinvar.omim
dbnsfp.interpro_domain
emv.egl_protein
emv.egl_variant
emv.hgvs

**Comment by kkrysiak** [comment]
It would be nice to have link outs where available. 

Clinvar is easy with the variant_id. For example: https://www.ncbi.nlm.nih.gov/clinvar/variation/13961/ 
cosmic is similar excluding the COSM of the id. For example: http://cancer.sanger.ac.uk/cosmic/mutation/overview?id=476

When considering these things, here is another myvariant.info example. http://myvariant.info/v1/variant/chr17:g.7579472G%3EC

**Comment by acoffman** [comment]
This now all getting pulled in and linked!

**Comment by kkrysiak** [comment]
web examples:
dbSNP 
https://www.ncbi.nlm.nih.gov/SNP/snp_ref.cgi?rs=763016003
OMIM
http://omim.org/entry/191170

**Comment by kkrysiak** [comment]
Since we don't seem to be getting anything from exac non-TCGA adjusted allele frequency I think we should move that entry from the static box and into the MyVariant.Info pop up and replace it with the general adjusted allele frequency. This isn't provided directly by MyVariant.Info, it will need to be calculated from existing MyVariant.Info parameters.

This requires getting the exac adjusted allele count (exac.ac_adj) and the exac adjusted allele number (exac.an_adj). Then just calculate the frequency which is allele count divided by allele number (aka total number of alleles).

exac.ac_adj/exac.an_adj

Allele count and allele number could then be in the MyVariant.Info pop up.

**Comment by acoffman** [comment]
This should be pretty easy to do! Do we want to truncate to a couple digits for display purposes or do we want to display the full result of the division?

**Comment by jmcmichael** [comment]
Should we indicate in the UI in some way that we calculate this instead of getting it directly from my variant info?

**Comment by kkrysiak** [comment]
@malachig @obigriffith, what do you think about indicating this? I mean, that's how they calculate it on their website and is the format that people would expect to see in the information in.

Maybe in the pop up window you can show the 3 fields (adjusted allele count, adjusted allele number and adjusted allele frequency) but after the allele frequency just put [calculated] in grey or something? That way all 3 figures are together.

**Comment by kkrysiak** [comment]
Or I guess the formula itself [Adj AC/Adj AN] in grey?

**Comment by obigriffith** [comment]
Yeah. I like the idea of showing the two fields that are natively available and then the calculated field with formula indicated to show a calculation has been done on our end.

**Comment by kkrysiak** [comment]
@acoffman, I think rounding digits is perfectly reasonable. I would show at least 5 digits after the decimal place though. You could make a display choice of just showing <0.00001 for numbers below that potentially, if scientific notation is not preferred. I would rather have 0.001 than 1x10^-3 for the higher allele frequencies (>0.00001) though because it is easier for my brain to process than scientific notation.
