### ISSUE TITLE
Can't view events on dev instance

### ISSUE THREAD

**Issue by ahwagner** [genome/civic-server#253]
Events on the activity page (see http://54.202.232.211:3000/#/activity) don't lead anywhere when clicked on the dev AMI. Production site is fine.

This was first noticed by @arpaddanos when trying to view submitted evidence in his instance.

**Comment by acoffman** [comment]
So, this is being triggered by an 'undefined method `status` for source` error on the server side. This is weird because that method exists by default as there is a `status` column in the `source` table. Have you run the latest migrations in the AMI? That's all I can think might be causing it, but I would expect to see a lot more issues than just that if the database wasn't current.

**Comment by ahwagner** [comment]
yeah, migrations have been run. I'll leave an instance running [here](http://54.214.127.216:3001/#/browse/variants) for bug-fixing. Credentials in slack.

**Comment by ahwagner** [comment]
@acoffman fixed this by pushing an updated database to the AMI.
