### ISSUE TITLE
preserve lowercase letters in variant names on add evidence POST

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-server#308]
Variant names should be allowed to include lowercase letters due to the cases detailed in genome/civic-client#737.

**Comment by acoffman** [comment]
So, as @jmcmichael noted, the server currently enforces that all variant names be upper case. I can't find the issue at the moment but this was an intentional decision at the time. One of the goals was to sidestep the problem of people entering the same variant names formatted slightly differently. I think its still valuable to prevent that from happening; but yeah, its clear we also need to support lowercase letters in variant names.

That being said, here's what I plan to do unless anyone has any objections:

 * When a variant name comes in from the frontend (edit form, add form, etc) check for an existing variant using a case __insensitive__ query.
 * If the user-entered variant matches an existing variant but differs only in case, assume they are the same variant.
 * Otherwise, treat it as a new variant and preserve the user-entered formatting of the name.

Does this sound good @malachig?

**Comment by kkrysiak** [comment]
I like this approach. The only thing I wonder about is how that will work in the dropdown. Ideally, they would just pick the existing one so there will be no differences.

**Comment by acoffman** [comment]
Yeah, I would anticipate the dropdown/typeahead will continue to function as it currently does!

**Comment by acoffman** [comment]
This is resolved for the normal variant creation path (add/edit evidence form). I will still need to address this in the importers.
