### ISSUE TITLE
Comment badge inconsistency

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-server#314]
It looks like Gold Commentor badge is awarded at 200 comments. I have (currently) 362 comments showing on my profile page but only bronze and silver Commentor badges. Maybe there is a disconnect in how comments are counted for the profile summary vs badge awarding?

**Comment by acoffman** [comment]
Yeah, there is a discrepancy in the way things are counted/displayed. The higher number is all comments you've made (which includes the automatically attached comments on things like evidence submissions), the smaller number is the number of comments that you've made independently of other submissions (ie: where you just went to an entity and commented on it). The smaller number is the one used for badge calculations.

I've updated the query to display the "correct" count on profile pages. I do notice that you now have > 200 comments by either count though and don't have the badge yet so that's a different issue. Looking into that now!
