### ISSUE TITLE
Additional stats endpoint(s)

### ISSUE THREAD

**Issue by acoffman** [genome/civic-server#47]
We'd like a dashboard of sorts for displaying information general site information, activity, and stats. We'll need endpoints to power them. Some ideas:

 * Total database size (number of evidence items, variants, users, etc)
 * Recent activity
 * New users

**Comment by malachig** [comment]
I created a list of ideas in this space at some point but can't seem to find the email or issue now.
- Grand total: number of publications, genes, variants, drugs, diseases, and evidence statements

- New items of each of these categories in the last week, month, year.  Perhaps this concept could be covered by some graphics instead of a table of numbers.

- Broken down by evidence type. Number of evidence statements that are: predictive, prognostic, diagnostic.
- Broken down by evidence level. Number of evidence statements that are: A, B, C, D, E
- Broken down by variant origin.  Number of evidence statements that are: germline or somatic
- Broken down by trust rating.  Number of evidence statements that are: 1, 2, 3, 4, or 5 stars.

A user specific dashboard would also be useful:
- Number of edits, number of evidence items added

**Comment by acoffman** [comment]
(I've been bad about closing these out, so apologies in advance for a bunch of spam incoming)

Stats endpoints added:

`/api/stats/site` will give basic site overview information. For Genes, Users, Evidence Items, Comments, Variants, Drugs, and Diseases, it will give total counts, total new this week, this month and this year. Additionally it will give number of pending edits and number of accepted edits.

`/api/stats/current_user` will give a logged in user stats about their contributions, including total number of comments, submitted evidence items, suggested edits, accepted edits, and rejected edits.

`/api/stats/evidence_items` will give breakdowns of evidence item counts by origin, level, and type
