### ISSUE TITLE
Page not found in API documentation

### ISSUE THREAD

**Issue by Shane-Neeley** [genome/civic-server#63]
The examples are not working .. getting a 404 error.

https://civic.genome.wustl.edu/api/genes/238/variants/5

**Comment by acoffman** [comment]
Thanks for the report - it looks like our API documentation needs to be re-worked a bit! We will address that in our next release.

**Comment by Shane-Neeley** [comment]
Thanks Adam,

In the mean time, can you tell me how it has changed?

Shane

**Comment by acoffman** [comment]
Sure thing. We've made two primary changes since that documentation was written:

* We've stopped using entrez ids in the Gene endpoints in favor of using internal ids for now
* We've reduced the amount of nesting to a maximum of one level. You can now get an 'index' endpoint one layer down, but no further. In other words:

You can get a list of genes:
`/api/genes`
And then get a list of variants for a given gene:
`/api/genes/:id/variants`
But you can no longer continue to nest. To get a list of evidence items for a given variant, you would do the following:
`/api/variants/:id/evidence_items`

Similarly, the comments, revisions, suggested changes, etc are all now at the "top level" for the entity in question:

`/api/variants/:id/comments`
`/api/evidence_items/:id/revisions`

etc.

Hopefully that's helpful!

**Comment by Shane-Neeley** [comment]
Thanks Adam that helps. Civics variant descriptions are great. We hope we can provide annotation back to civic once we start working with more researchers. 




Shane Neeley

Software Engineer 

Molecularmatch.com

**Comment by acoffman** [comment]
Improved documentation has gone out which should help clarify much of this. We will continue to improve the docs and provide more examples as we go forward!
