### ISSUE TITLE
Pending evidence can be viewed by everyone

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-server#68]
I'm moving this issue from civic-client (genome/civic-client#146), as it seems like this should be handled on the server side. KK's orginal text:

"Even when you aren't signed in, pending evidence statements can be viewed prior to being accepted by an admin."

**Comment by acoffman** [comment]
What pages are you seeing this on? The 'evidence item index' view filters down to only active items if you don't explicitly supply a status to query for, and I don't think the main "browse" view shows individual evidence items.

**Comment by kkrysiak** [comment]
This happened when we entered a new evidence item for a variant that didn't previously exist. I'll see if I can replicate this behavior.

**Comment by kkrysiak** [comment]
I submitted a new evidence statement EID436 for BTK C481S through the Add Evidence page. This evidence statement is currently viewable to anyone. This has not been through any additional approval. I'm not sure if this behavior is because I'm an admin (there is no "apply" button to directly add and approve the statement on the add evidence page), because this evidence item required the creation of a new variant and gene in the database or something else entirely.

**Comment by malachig** [comment]
We might actually want it to be the true that admins can see new evidence statements even before they are approved.  Ideally admins would eventually be able to see and approve new evidence items right in the UI instead of the admin interface.  However, not sure if this explains what you are seeing.  Maybe try creating a new account with a different email address and confirm whether a non admin can see these?

**Comment by kkrysiak** [comment]
I can see it when I'm not logged in at all or logged in as a non-admin user.

**Comment by malachig** [comment]
Oh.  Ok, good to know.  I guess that is clearly not what we want then...

**Comment by acoffman** [comment]
Fixed in latest!
