### ISSUE TITLE
migrate error

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#79]
I am seeing this error on a local instance with the latest version of client and server.

```
ActiveRecord::PendingMigrationError - 

Migrations are pending. To resolve this issue, run:

	bin/rake db:migrate RAILS_ENV=development
```

If I run that command:
```
Malachis-MacBook-Pro:civic-server mgriffit$ bin/rake db:migrate RAILS_ENV=development

== 20150728191648 AddStateParamsColumnToEvents: migrating =====================
-- add_column(:events, :state_params, :text)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateColumn: ERROR:  column "state_params" of relation "events" already exists
: ALTER TABLE "events" ADD "state_params" text/Users/mgriffit/git/civic/civic-server/db/migrate/20150728191648_add_state_params_column_to_events.rb:3:in `change'
ActiveRecord::StatementInvalid: PG::DuplicateColumn: ERROR:  column "state_params" of relation "events" already exists
: ALTER TABLE "events" ADD "state_params" text
/Users/mgriffit/git/civic/civic-server/db/migrate/20150728191648_add_state_params_column_to_events.rb:3:in `change'
PG::DuplicateColumn: ERROR:  column "state_params" of relation "events" already exists
/Users/mgriffit/git/civic/civic-server/db/migrate/20150728191648_add_state_params_column_to_events.rb:3:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by malachig** [comment]
Looks like Nick is getting this error as well now.

**Comment by acoffman** [comment]
It looks like somehow the data dump is out of sync with the migrations - if you open the console and run `ActiveRecord::SchemaMigration.create(version: "20150728191648")` it should tell rails that the migration has already been run. I'm looking into how they could have gotten out of sync!

**Comment by acoffman** [comment]
Alright, I've pushed a fresh data dump up which should avoid this problem. I'm still now sure how it got out of sync, but here's what happened:

* A version of the schema was loaded that contained the recently added column `state_params`
* A version of the data dump was loaded (the data dump contains a table indicating which migrations have already been run) that believed that the migration to add `state_params` had not yet been run
* This triggers a "Pending Migrations, please run rake db:migrate" error
* Running db:migration throws an error because its trying to add a column that is, in fact, already present.
