### ISSUE TITLE
Variant PDGFRA V536E exists without evidence statement

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-server#84]
Is this a known issue?  A failure during import? I don't think it should be possible to have a variant without at least one evidence statement.

https://civic.genome.wustl.edu/#/events/genes/38/summary/variants/97/summary

**Comment by malachig** [comment]
Perhaps this is also why V536E doesn't appear in the quick search results as well?

**Comment by acoffman** [comment]
That is actually exactly why it doesn't appear in the quick search! The quick search uses an inner join which won't return a variant unless it has evidence items whereas the view scope was using a left join which will return it either way.

I have adjusted the queries to exclude variants with no evidence items. 

As for how the variant got in there - I'm not sure. At first I suspected it was due to the partial import of the UBC data, but that doesn't appear to be the case. This variant doesn't appear in either our import/clinicalevidence tsv or the UBC tsv. The audit log traces its creation back to June, but it predates us tracking users reliably, so I just have "Admin" as the creator.

It will no longer show up on the site (the frontend does some caching so you may need to do a hard-refresh to get it to go away).
