### ISSUE TITLE
Add evidence losing many details

### ISSUE THREAD

**Issue by obigriffith** [genome/civic-server#85]
I just submitted a new piece of evidence for a new variant of an existing gene. Specifically, I wanted to create an entry for ERBB2 OVEREXPRESSION. Something the we should really cover. Filling out the submission form went smoothly and seemed to submit successfully. However, when I went to the admin interface to approve it, most critical details are missing including: gene, variant, drug, disease, and source!

![screenshot 2015-08-25 10 44 48](https://cloud.githubusercontent.com/assets/1638042/9471645/f01b746e-4b16-11e5-9e6d-de41bd3b236f.png)
![screenshot 2015-08-25 10 46 12](https://cloud.githubusercontent.com/assets/1638042/9471644/f019bdae-4b16-11e5-9feb-402220a9a60d.png)

**Comment by acoffman** [comment]
This evidence item has a status of "submitted" which means it has not been processed by the background workers yet. The information is not lost, it just hasn't been populated yet. It will transition to a state of `failed` or `processed` at which point you can either correct or approve it. I just checked and it looks like its still sitting in the `submitted` state, so I'll see if I can't figure out what's taking so long.

**Comment by obigriffith** [comment]
Two revent new evidence items both took a long time (1-2hrs?) before switching to failed state. I don't know why they failed. I'm not sure how to fix them in the admin interface because:
1) Variant is still blank and can only be entered from drop down list (what if it is a new variant?) and I'm not sure which of the many "OVEREXPRESSION" options to choose. Maybe it makes no difference. In which case we should provide just the unique list as well as an option for a new variant
2) There is no option to edit gene and yet this still shows as empty.
3) Can't enter drug because Trastuzumab is not currently in the dropdown list of options for drugs.
4) No way to enter disease.
5) Can't enter source because it is not in dropdown list.

**Comment by acoffman** [comment]
Ah yes, I see what you're saying. In the event of a failure to process, its super cumbersome to make the proper corrections. (For instance, you could go to the variants tab and create a variant there, at which point it will appear in the drop down; but that's clearly crummy). It also definitely shouldn't take 4 hours to process. I will work on both this afternoon.

**Comment by acoffman** [comment]
In reference to this issue and #78, I am re-working the submit evidence item process. The background processing was needed because we were dependent on filling in information from so many external sources (Disease Ontology, Entrez, MyGene.info, etc) and a.) we didn't want our submit evidence form to stop working if any of those sites had downtime, and b.) we hitting all of those external APIs during the normal form submit made it really slow.

Now with local mirrors of the disease ontology and Entrez gene symbols/mygene.info aliases, the only external thing we really need to hit is pubmed (to pull down a citation if we haven't seen that pubmed id before).

I think this gets us to the point where we can eliminate the background processing altogether (as its been a source of both bugs and confusion since its inception). I hope to have a new version out today or tomorrow that just accepts the evidence item and sends it straight to the "awaiting approval by an admin" stage.

This should be simpler and more streamlined than we we had before.
