### ISSUE TITLE
Some variant pages do not load or are invalid?

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#86]
Not sure if this is a client or server issue.

On the live site I am seeing some strange behavior for some of the variants in this variant group:
https://civic.genome.wustl.edu/#/events/genes/52/summary/variantGroups/12/summary

These two variants do not load.  When you click on them nothing happens:
https://civic.genome.wustl.edu/#/events/genes/52/summary/variants/146/summary
https://civic.genome.wustl.edu/#/events/genes/30/summary/variants/147/summary

Other variants in this group load fine.  Maybe these variants were entered at some point but have no evidence and that is the problem.  Perhaps this is a known issue that is already resolved...

**Comment by Shane-Neeley** [comment]
When looking at BRAF, you see a variant listed
https://civic.genome.wustl.edu/api/genes/5
{"name": "V600R", "id": 16}

But when trying to access that variant by id, it returns nothing.
https://civic.genome.wustl.edu/api/variants/16
{"status":"404","error":"Not Found"}

**Comment by acoffman** [comment]
@Shane-Neeley this is occurring because there are no evidence items for that particular variant. I'm not sure how it ended up in there, but our data model assumes that if a variant is present, it will have one or more evidence items. The variants endpoint that you are hitting in your second request does an `inner join` from variants to evidence items to eagerly load them. As there are no evidence items, nothing comes back from the query. 

For now I've soft-deleted that variant so the initial response's variant list will be "correct." I'm going to go back through our logs and import spreadsheets to see if I can identify how we ended up with an evidence item-less variant in the system (a bug with a bulk import, a bug in an early version of the site, or perhaps just some bad initial data).

**Comment by Shane-Neeley** [comment]
Thanks @acoffman that makes sense. I noticed these are empty. Not sure if it is all of them.

https://civic.genome.wustl.edu/api/variants/51
https://civic.genome.wustl.edu/api/variants/60
https://civic.genome.wustl.edu/api/variants/61
https://civic.genome.wustl.edu/api/variants/70
https://civic.genome.wustl.edu/api/variants/68
https://civic.genome.wustl.edu/api/variants/71
https://civic.genome.wustl.edu/api/variants/147
https://civic.genome.wustl.edu/api/variants/84
https://civic.genome.wustl.edu/api/variants/146
https://civic.genome.wustl.edu/api/variants/237
https://civic.genome.wustl.edu/api/variants/235
https://civic.genome.wustl.edu/api/variants/234
https://civic.genome.wustl.edu/api/variants/166
https://civic.genome.wustl.edu/api/variants/15
https://civic.genome.wustl.edu/api/variants/16
https://civic.genome.wustl.edu/api/variants/26
https://civic.genome.wustl.edu/api/variants/90
https://civic.genome.wustl.edu/api/variants/91
https://civic.genome.wustl.edu/api/variants/97
https://civic.genome.wustl.edu/api/variants/109
https://civic.genome.wustl.edu/api/variants/162
https://civic.genome.wustl.edu/api/variants/111
https://civic.genome.wustl.edu/api/variants/120
https://civic.genome.wustl.edu/api/variants/126
https://civic.genome.wustl.edu/api/variants/228
https://civic.genome.wustl.edu/api/variants/229
https://civic.genome.wustl.edu/api/variants/115

**Comment by acoffman** [comment]
@Shane-Neeley Thanks for the list! I have cleaned up all variants that are missing evidence items. This should fix both the API responses and the page load issues. I am continuing to look into how these got generated in the first place!
