### ISSUE TITLE
Currently can not view the BRAF entry?

### ISSUE THREAD

**Issue by malachig** [genome/civic-server#96]
A few of us have noted that some gene views and any variants associated with those genes can not be viewed in the public instance of CIViC.  For example, currently `BRAF` (one of the most richly curated) does not load.

Not sure if there are any other genes experiencing this problem but there could be.  Is there a way we can automate checking such things?

**Comment by acoffman** [comment]
This is working again now. This is actually caused by a bit of a unique situation in that its a result of the old Evidence Item that's still pending approval (waiting on the backend ability to add a new source). Its in a state that new evidence items will not be able to get into. I had previously hotfixed a special case in for that one particular item, but the deploy earlier this week blew that away. I'll see about adding some automated tests for this issue going forward though!

**Comment by malachig** [comment]
Looks good now.  Thanks for the rapid fix @acoffman
