### ISSUE TITLE
need a 'reject' endpoint for suggested evidence items

### ISSUE THREAD

**Issue by jmcmichael** [genome/civic-server#97]
We've got an 'accept' endpoint, but it looks like we don't have the complementary 'reject' option - and I'd like to provide both options to editors on the evidence item summary view.

**Comment by malachig** [comment]
Quick thought. 

For complex entries like evidence item maybe we could ultimately have the reject concept be accompanied by a `revive` concept?  That way the person who had their item rejected can give it another try by modifying their previous submission instead of creating it from scratch.

I have noticed a few times that when variant coordinates for example are not quite right, I either (A) accept and then make a new revision to patch the field that needed fixing, or (B) I reject and create a new revision from scratch.

In (A) the submitter may not get the feedback they need to improve their next submission or I may forget to patch the mistakes leading to quality issues.  

In (B) there is a lot of copying and pasting.

**Comment by acoffman** [comment]
Yeah, we definitely should have better lifecycle for submitted evidence items. Perhaps they themselves should support suggested changes or similar. I am going to close this issue (as a "reject" endpoint exists) but we should chat in the meeting today about the best way to accomplish this!
